// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAmL4xh-ULyn34IGYQqXH3mLMUhJ2VuNf4',
    appId: '1:349269572322:web:2784c44e15479fcb2a7cbb',
    messagingSenderId: '349269572322',
    projectId: 'chama-o-sindico-52d5b',
    authDomain: 'chama-o-sindico-52d5b.firebaseapp.com',
    storageBucket: 'chama-o-sindico-52d5b.firebasestorage.app',
    measurementId: 'G-79DVTXGWB7',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAdRLTVj3JNJp4RY-3S0KoJcUZsP1cFW7M',
    appId: '1:349269572322:android:3e17e672f31dedd42a7cbb',
    messagingSenderId: '349269572322',
    projectId: 'chama-o-sindico-52d5b',
    storageBucket: 'chama-o-sindico-52d5b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDUFQYzoGgO_uFwlIF8VPbqLulNoTeR-Ig',
    appId: '1:349269572322:ios:e42cb99101e16ad22a7cbb',
    messagingSenderId: '349269572322',
    projectId: 'chama-o-sindico-52d5b',
    storageBucket: 'chama-o-sindico-52d5b.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDUFQYzoGgO_uFwlIF8VPbqLulNoTeR-Ig',
    appId: '1:349269572322:ios:e42cb99101e16ad22a7cbb',
    messagingSenderId: '349269572322',
    projectId: 'chama-o-sindico-52d5b',
    storageBucket: 'chama-o-sindico-52d5b.firebasestorage.app',
    iosBundleId: 'com.example.client',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAmL4xh-ULyn34IGYQqXH3mLMUhJ2VuNf4',
    appId: '1:349269572322:web:396d0b158e4d06e32a7cbb',
    messagingSenderId: '349269572322',
    projectId: 'chama-o-sindico-52d5b',
    authDomain: 'chama-o-sindico-52d5b.firebaseapp.com',
    storageBucket: 'chama-o-sindico-52d5b.firebasestorage.app',
    measurementId: 'G-5L4MLB7TJL',
  );
}
